package futbolEnPapel2013;

import futbolEnPapel2013.fondo.Fondo;
import java.awt.Color;
import java.awt.Image;

/**
 * Clase en la que se muestran los créditos
 * @author Marcos Martín Pozo Delgado
 * @version 1.0
 */
public class AcercaDe extends javax.swing.JDialog {

    /**
     * Contenedor con la imagen que se quiere poner como fondo
     */
    private final Fondo contenedor
            = new Fondo("/recursos/fondo.png");

    /** Constructor */
    public AcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setContentPane(contenedor);
        initComponents();
    }

    /**
     * Método set con la ruta como parámetro
     * @param nombreImagen
     */
    public void setImagen(String nombreImagen) {
        contenedor.setImagen(nombreImagen);
    }

    /**
     * Método set con la imagen como parámetro
     * @param nuevaImagen
     */
    public void setImagen(Image nuevaImagen) {
        contenedor.setImagen(nuevaImagen);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoCreditos = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        titulo = new javax.swing.JTextField();
        version = new javax.swing.JTextField();
        contactoTexto = new javax.swing.JTextField();
        contactoCuerpo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");
        setName("creditos"); // NOI18N
        setResizable(false);

        cuerpoCreditos.setBackground(new Color(0, 0, 0, 0));
        cuerpoCreditos.setEditable(false);
        cuerpoCreditos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cuerpoCreditos.setForeground(new java.awt.Color(187, 187, 187));
        cuerpoCreditos.setText("Desarrollo: Marcos Martín Pozo Delgado");
        cuerpoCreditos.setBorder(null);

        boton.setFont(new java.awt.Font("Papyrus", 1, 24));
        boton.setText("Volver al menú principal");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
        });

        titulo.setBackground(new Color(0, 0, 0, 0));
        titulo.setEditable(false);
        titulo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(187, 187, 187));
        titulo.setText("Fútbol en papel 2013");
        titulo.setBorder(null);

        version.setBackground(new Color(0, 0, 0, 0));
        version.setEditable(false);
        version.setFont(new java.awt.Font("Calibri", 0, 18));
        version.setForeground(new java.awt.Color(187, 187, 187));
        version.setText("Versión: 1.0.0");
        version.setBorder(null);

        contactoTexto.setBackground(new Color(0, 0, 0, 0));
        contactoTexto.setEditable(false);
        contactoTexto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        contactoTexto.setForeground(new java.awt.Color(187, 187, 187));
        contactoTexto.setText("Dirección de contacto:");
        contactoTexto.setBorder(null);

        contactoCuerpo.setBackground(new Color(0, 0, 0, 0));
        contactoCuerpo.setEditable(false);
        contactoCuerpo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        contactoCuerpo.setForeground(new java.awt.Color(187, 187, 187));
        contactoCuerpo.setText("marcos.martin.pozo.delgado@gmail.com");
        contactoCuerpo.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuerpoCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactoCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(cuerpoCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactoCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonMouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextField contactoCuerpo;
    private javax.swing.JTextField contactoTexto;
    private javax.swing.JTextField cuerpoCreditos;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField version;
    // End of variables declaration//GEN-END:variables

}
