
package futbolEnPapel2013;

import futbolEnPapel2013.fondo.Fondo;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * Clase principal del juego FIFA Paper 2010
 * @author Marcos Martín Pozo Delgado
 * @version 1.0
 */
public class FutbolEnPapel2013 extends javax.swing.JFrame {

    /**
     * Variable que indica el color del tablero de juego (inicializada a false
     * en el constructor)
     */
    private boolean tableroNegro;

   
    /**
     * Variable que indica cuál es el jugador 1
     */
    private int jug1;

    /**
     * Variable que indica cuál es el jugador 2
     */
    private int jug2;

    /**
     * Variable que indica el nivel de dificultad del jugador 1
     * (inicializada a 1 en el constructor)
     */
    private int nivel1;

    /**
     * Variable que indica el nivel de dificultad del jugador 2
     * (inicializada a 1 en el constructor)
     */
    private int nivel2;


    /**
     * Contenedor con la imagen que se quiere poner como fondo
     */
    private final Fondo contenedor
            = new Fondo("/recursos/principal.png");

    /**
     * Constructor por defecto
     */
    public FutbolEnPapel2013() {
        
        setContentPane(contenedor);
        tableroNegro = false;
        jug1 = Juego.PERSONA;
        jug2 = Juego.CPU;
        nivel1 = 1;
        nivel2 = 1;
        initComponents();
    }

    /**
     * Método get del atributo del color del tablero
     * @return true si el tablero es negro y false en caso contrario
     */
    public boolean getTableroNegro() {
       return tableroNegro;
    }

    /**
     * Método set del atributo del color del tablero
     * @param negro
     */
    public void setTableroNegro(boolean negro) {
        tableroNegro = negro;
    }

    
    /**
     * Método get del atributo del jugador 1
     * @return El tipo del jugador 1
     */
    public int getJug1() {
        return jug1;
    }

    /**
     * Método set del atributo del jugador 1
     * @param tipo
     */
    public void setJug1(int tipo) {
        jug1 = tipo;
    }

     /**
     * Método get del atributo del jugador 2
     * @return El tipo del jugador 2
     */
    public int getJug2() {
        return jug2;
    }

    /**
     * Método set del atributo del jugador 2
     * @param tipo
     */
    public void setJug2(int tipo) {
        jug2 = tipo;
    }

    /**
     * Método get del atributo del nivel1 de dificultad
     * @return El nivel1 de dificultad
     */
    public int getNivel1() {
        return nivel1;
    }

    /**
     * Método set del atributo del nivel1 de dificultad
     * @param nuevo
     */
    public void setNivel1(int nuevo) {
        nivel1 = nuevo;
    }

      /**
     * Método get del atributo del nivel2 de dificultad
     * @return El nivel2 de dificultad
     */
    public int getNivel2() {
        return nivel2;
    }

    /**
     * Método set del atributo del nivel2 de dificultad
     * @param nuevo
     */
    public void setNivel2(int nuevo) {
        nivel2 = nuevo;
    }

    /**
     * Método set con la ruta como parámetro
     * @param nombreImagen
     */
    public void setImagen(String nombreImagen) {
        contenedor.setImagen(nombreImagen);
    }

    /**
     * Método set con la imagen como parámetro
     * @param nuevaImagen
     */
    public void setImagen(Image nuevaImagen) {
        contenedor.setImagen(nuevaImagen);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJugar = new javax.swing.JButton();
        botonOpciones = new javax.swing.JButton();
        botonInstrucciones = new javax.swing.JButton();
        botonAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fútbol en papel 2013");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/recursos/balon.png")).
            getImage());
        setResizable(false);

        botonJugar.setFont(new java.awt.Font("Papyrus", 1, 24));
        botonJugar.setText("Jugar");
        botonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonJugarMouseClicked(evt);
            }
        });

        botonOpciones.setFont(new java.awt.Font("Papyrus", 1, 24));
        botonOpciones.setText("Opciones");
        botonOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOpcionesMouseClicked(evt);
            }
        });

        botonInstrucciones.setFont(new java.awt.Font("Papyrus", 1, 24));
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInstruccionesMouseClicked(evt);
            }
        });

        botonAcercaDe.setFont(new java.awt.Font("Papyrus", 1, 24));
        botonAcercaDe.setText("Acerca de");
        botonAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAcercaDeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAcercaDe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(botonInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(botonOpciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(botonJugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(botonJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInstrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAcercaDe)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcercaDeMouseClicked
        // TODO add your handling code here:
        AcercaDe creditos = new AcercaDe(this, false);
        creditos.setVisible(true);
    }//GEN-LAST:event_botonAcercaDeMouseClicked

    private void botonInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInstruccionesMouseClicked
        // TODO add your handling code here:
        Instrucciones instrucciones = new Instrucciones(this, false);
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesMouseClicked

    private void botonOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOpcionesMouseClicked
        // TODO add your handling code here:
        Opciones opciones = new Opciones(this, false);
        opciones.setVisible(true);
    }//GEN-LAST:event_botonOpcionesMouseClicked

    private void botonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseClicked
        // TODO add your handling code here:
        Juego juego = null;
        try {
            juego = new Juego(this, false);
            juego.setVisible(true);
            juego.jugar();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonJugarMouseClicked

   /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FutbolEnPapel2013().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcercaDe;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonOpciones;
    // End of variables declaration//GEN-END:variables

}
