package futbolEnPapel2013;

import futbolEnPapel2013.fondo.Fondo;
import java.awt.Color;
import java.awt.Image;

/**
 * Clase que implementa la ventana de instrucciones
 * @author Marcos Martín Pozo Delgado
 * @version 1.0
 */
public class Instrucciones extends javax.swing.JDialog {

    /**
     * Contenedor con la imagen que se quiere poner como fondo
     */
    private final Fondo contenedor
            = new Fondo("/recursos/fondo.png");

    /** Constructor */
    public Instrucciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setContentPane(contenedor);
        initComponents();
    }

    /**
     * Método set con la ruta como parámetro
     * @param nombreImagen
     */
    public void setImagen(String nombreImagen) {
        contenedor.setImagen(nombreImagen);
    }

    /**
     * Método set con la imagen como parámetro
     * @param nuevaImagen
     */
    public void setImagen(Image nuevaImagen) {
        contenedor.setImagen(nuevaImagen);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new javax.swing.JButton();
        desplazamientoInstrucciones = new javax.swing.JScrollPane();
        textoInstrucciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instrucciones");
        setName("instrucciones"); // NOI18N
        setResizable(false);

        boton.setFont(new java.awt.Font("Papyrus", 1, 24));
        boton.setText("Volver al menú principal");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
        });

        desplazamientoInstrucciones.setBackground(new Color(0, 0, 0, 0));
        desplazamientoInstrucciones.setBorder(null);

        textoInstrucciones.setBackground(new Color(0, 0, 0, 0));
        textoInstrucciones.setColumns(20);
        textoInstrucciones.setEditable(false);
        textoInstrucciones.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        textoInstrucciones.setForeground(new java.awt.Color(187, 187, 187));
        textoInstrucciones.setRows(5);
        textoInstrucciones.setText("El objetivo del juego es meter gol en la portería contraria (la\nde arriba para el jugador 1 y la de abajo para el 2) o conseguir\nque el contrario se bloquee (no tenga opción de movimiento).\n\n    El juego comienza en el medio del campo, y en cada\nturno el jugador puede mover el balón hacia cualquier\nvértice de la cuadrícula accesible adyacente, mediante\nlas siguientes teclas:\n\n8: arriba, 2: abajo, 4: izquierda, 6: derecha,\n7: diagonal superior izquierda, 9: diagonal superior derecha,\n1: diagonal inferior izquierda, 3: diagonal inferior derecha.\n\n    Un vértice es accesible si el camino para llegar a él no ha\nsido usado por ningún jugador (no está marcado con\nningún color) ni es pared ni línea central.\n\n    Si se accede a un vértice al que ya ha accedido algún\njugador (alguno de los caminos para llegar a él está\nmarcado o éste forma parte de una pared o de la línea\ncentral), el balón rebota y el jugador tiene 4 segundos para\nrealizar otro movimiento.\n");
        textoInstrucciones.setBorder(null);
        textoInstrucciones.setMinimumSize(new java.awt.Dimension(428, 490));
        textoInstrucciones.setPreferredSize(new java.awt.Dimension(428, 490));
        desplazamientoInstrucciones.setViewportView(textoInstrucciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desplazamientoInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(desplazamientoInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_botonMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JScrollPane desplazamientoInstrucciones;
    private javax.swing.JTextArea textoInstrucciones;
    // End of variables declaration//GEN-END:variables

}
