package futbolEnPapel2013.fondo;

import java.awt.*;
import javax.swing.*;

/**
 * Clase que implementa el contenedor para tener una imagen como fondo
 * @author Marcos Martín Pozo Delgado
 * @version 1.0
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Imagen que se desea poner como fondo
     */
    private Image imagen;

    /**
     * Constructor con la ruta de la imagen como parámetro
     * @param nombreImagen
     */
    public Fondo(String nombreImagen) {
        initComponents();
        if (nombreImagen != null) {
            imagen = new ImageIcon(getClass().getResource(nombreImagen)).
                    getImage();
        }
    }

    /**
     * Constructor con la imagen como parámetro
     * @param imagenInicial
     */
    public Fondo(Image imagenInicial) {
        initComponents();
        if (imagenInicial != null) {
            imagen = imagenInicial;
        }
    }

    /**
     * Método set con la ruta como parámetro
     * @param nombreImagen
     */
    public void setImagen(String nombreImagen) {
        if (nombreImagen != null) {
            imagen = new ImageIcon(getClass().getResource(nombreImagen))
                    .getImage();
        } else {
            imagen = null;
        }

        repaint();
    }

    /**
     * Método set con la imagen como parámetro
     * @param nuevaImagen
     */
    public void setImagen(Image nuevaImagen) {
        imagen = nuevaImagen;

        repaint();
    }

    /**
     * Método que pinta la imagen
     * @param g
     */
    @Override
    public void paint(Graphics g) {
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
        } else {
            setOpaque(true);
        }

        super.paint(g);
    }
     /** Constructor por defecto */
    public Fondo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


   
}
